Replace watir-webdriver with watir
Watir-webdriver has been moved and maintenance is now in the watir
gem. Update gemspec to reflect, fixes:

```
watir-webdriver/elements/table_cell.rb:6:in `alias_method':
undefined method `col_span' for class `Watir::TableCell'
(NameError)
```